### ISSUE TITLE
Item search grid can't be adjusted to fit quad tab in 1920x1080

### ISSUE THREAD

**Issue by tfp** [DeadlyCrush/DeadlyTrade#17]
The quad overlay "snaps" in and reacts not fine granular enough.
![image](https://user-images.githubusercontent.com/1092714/76143638-5fa24200-6079-11ea-973a-96ce963604f0.png)

**Comment by DeadlyCrush** [comment]
Grid logic is also full changed in 1.4.0.1 version.
I will release update version in the season break, which is work in progress my major plan and priority. Because the release is more meaningful before and after the season break.

**Comment by DeadlyCrush** [comment]
Grid logic is also full changed in 1.4.0.1 version. Fixed.
