### ISSUE TITLE
Keyboard shortcuts are still captured even if bound option is disabled

### ISSUE THREAD

**Issue by tfp** [DeadlyCrush/DeadlyTrade#19]
Disabled the emergency shortcut (I really suggest to to this by default) because it got in the way of other shortcuts (space is used for a flask and together with control = skill bar swap, you really hit that often enough...). Result after disbling the option: it's not triggered anymore, but the key press got still captured and got not transfered to PoE.
Workaround: you need to reconfiger the shortcut to somethung you really don't need even if you don't use the option. But I should not have to do this.

**Comment by DeadlyCrush** [comment]
HotKey logic is full changed in 1.4.0.1 version.
I will release update version in the season break, which is work in progress my major plan and priority. Because the release is more meaningful before and after the season break.

**Comment by DeadlyCrush** [comment]
HotKey logic is full changed in 1.4.0.1 version. Fixed
