### ISSUE TITLE
You may need privilege rights...? Language?

### ISSUE THREAD

**Issue by Shinzor** [DeadlyCrush/DeadlyTrade#26]
Since today the addon self updated (i guess?) and it is no longer working, I first was getting a message like "please check if you are on the correct language" (or something similar) and after restarting a few times, im now getting "you may need privilege rights", however, I am opening it as admin.
Nothing else changed on my computer, as far as I know.
Playing on Kakao Korean version, game is in english.

Thank you for your hard work! :)

**Comment by DeadlyCrush** [comment]
@Shinzor Thank you for your kind words. You did right run add-on with kakao POE client. :) 

PS. about the 'run as admin'.
Overlay add-on can't work in kakao client. So, Kakao POE client user should run as admin all add-on which is using overlay. i will separate ggg and kakao next re-work version.

**Comment by DeadlyCrush** [comment]
Please make issue here if you anything need to help, question, suggestion. You can mention to me at discord server.
