### ISSUE TITLE
[Bug Report]Crash on startup, yet launcher still going - when runing without Admin Privileges

### ISSUE THREAD

**Issue by piotrszymaniec** [DeadlyCrush/DeadlyTrade#29]
**Describe the bug**
Program crashes when started without Admin Privileges. Then launcher still is runing. 

**To Reproduce**
1. Run DeadlyTrade.exe without admin rights
2. Click Start button in launcher

**Expected behaviour**
Nice message that "**program has to be run as Admin**".

**Screenshots**

<table>
<thead>
<tr>
<th>After crash (no Admin)</th><th>when work fine (admin)</th>
</tr>
</thead>
<tr>
<td><img width="250px" src="https://user-images.githubusercontent.com/5377285/80400598-51271880-88bb-11ea-882f-131a7b469ff1.png"></td>
<td><img width="250px" src="https://user-images.githubusercontent.com/5377285/80396717-584b2800-88b5-11ea-8d17-dd0f34e79b2f.png"></td>
</tr>
</table>

**log**
[deadlytrade.log](https://github.com/DeadlyCrush/DeadlyTrade/files/4540818/deadlytrade.log)

**system crash report**
https://pastebin.com/yJ0kKM8K

**Additional context**
Windows 7 x64, same happens with 2560x1440 and 1920x1200

**Comment by DeadlyCrush** [comment]
sorry for late reply. i use KAKAO client? normally GGG client not require admin privilege.

If you faced that error even though you use GGG client, I guess there is some different environment of your computer.

Please send to me ConfigPath.ini at Discord. (DM)

**Comment by DeadlyCrush** [comment]
KAKAO client user should run as administrator priviledge.
