### ISSUE TITLE
how i set a  custom localization

### ISSUE THREAD

**Issue by ppxb** [DeadlyCrush/DeadlyTrade#31]
First of all thanks for your hard working.
This a wonderful and amazing tool for POE.
But sometimes not all of the players good with English or Korean,so is there a way to support custom localization?
Thanks for your time.

**Comment by DeadlyCrush** [comment]
hard to figure out all lanuges' trade whisper format. trade whisper format is different by your trade site option, not related with in-game.ui lanuges option. so if add-on support all languages, add-on should know all languages' whisper format that each trade circumstances. until then I will focus decimal indicator that other country's keyboard option.

**Comment by ppxb** [comment]
Thanks for your reply.
Maybe my question is not clearly.I wanna know if there have a way to config the plugin UI interface's language which like ./localization/[KR/EN/RU].[conf/xml] or other things like this.
BTW, the original English enviroment will work better.
Thanks.

**Comment by DeadlyCrush** [comment]
Oh sorry. That's not possible set UI language to ru,de,fr etc... in this current version. UI will support eng & kor until fully overhauled, after then support other languages.

But add-on's every functions will support all languages. Thank you for your detailed suggestion and reply.

Stay healthy and have a good day.

**Comment by ppxb** [comment]
Thanks for you time.
It's a good news for me.
Stay healthy and have a nice day.
